version: '3.0'

services:
  app:
    build: .
    env_file:
      - tetatetchatbot.env
    networks:
      - tetatetnet
      - default
    depends_on:
      - mongodb
    ports: 
      - "8083:8080"

  mongodb:
    image: mongo:4
    restart: always
    volumes:
      - /tmp/data/db:/data/db
    networks:
      - tetatetnet
    command: mongod --smallfiles --logpath=/dev/null


networks:
  tetatetnet:

